// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User Login Data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Ends the session of a logged-in user by deleting the JWT token cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout User",
                "responses": {
                    "200": {
                        "description": "message: Logout successful",
                        "schema": {
                            "$ref": "#/definitions/MessagedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves the current user's username, role, and user ID from the JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "responses": {
                    "200": {
                        "description": "detail: Returns user session information",
                        "schema": {
                            "$ref": "#/definitions/UserSessionExtendedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/camera/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a list of cameras with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Retrieves lists cameras with optional search, type, and pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "inside",
                            "outside"
                        ],
                        "type": "string",
                        "description": "Camera type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CameraPaginatedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/camera/count/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a count of cameras",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Count returns total cameras count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "inside",
                            "outside"
                        ],
                        "type": "string",
                        "description": "Camera type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "count: 12345",
                        "schema": {
                            "$ref": "#/definitions/CountResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/camera/create/": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Creates new camera",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Creates a new camera",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CameraCreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CameraMessageResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/camera/{id}/delete/": {
            "delete": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Deletes a camera by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Deletes a camera",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Camera ID (int)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/UserMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/camera/{id}/detail/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve single camera detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Retrieve single camera",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Camera ID (int)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CameraResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/camera/{id}/update/": {
            "patch": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Updates an existing camera",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cameras"
                ],
                "summary": "Update a camera",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Camera ID (int)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CameraUpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/CameraMessageResponse"
                        }
                    },
                    "400": {
                        "description": "detail: BadRequest - invalid request",
                        "schema": {
                            "$ref": "#/definitions/BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "404": {
                        "description": "detail: User not found",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car-session/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CarSessionPaginatedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car-session/count/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "responses": {
                    "200": {
                        "description": "count: 12345",
                        "schema": {
                            "$ref": "#/definitions/CountResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car-session/event/entry/": {
            "post": {
                "tags": [
                    "Cars"
                ],
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "count: 12345",
                        "schema": {
                            "$ref": "#/definitions/CarSessionMessageResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car-session/event/exit/": {
            "post": {
                "tags": [
                    "Cars"
                ],
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "count: 12345",
                        "schema": {
                            "$ref": "#/definitions/CarSessionMessageResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a list of cars with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Retrieves lists cars with optional search, type, and pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CarPaginatedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car/count/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a count of cars",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Count returns total cars count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "count: 12345",
                        "schema": {
                            "$ref": "#/definitions/CountResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car/create/": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Creates new car",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Creates a new car",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CarCreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CarMessageResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car/{id}/detail/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve single car detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Retrieve single car",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID (int)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CarResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/car/{id}/update/": {
            "patch": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Updates an existing car",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Update a car",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID (int)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CarUpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/CarMessageResponse"
                        }
                    },
                    "400": {
                        "description": "detail: BadRequest - invalid request",
                        "schema": {
                            "$ref": "#/definitions/BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "404": {
                        "description": "detail: User not found",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tariff/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a list of tariffs with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tariffs"
                ],
                "summary": "Retrieves lists tariffs with optional search, type, and pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TariffPaginatedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tariff/count/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a count of tariffs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tariffs"
                ],
                "summary": "Count returns total tariffs count",
                "responses": {
                    "200": {
                        "description": "count: 12345",
                        "schema": {
                            "$ref": "#/definitions/CountResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tariff/create/": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Creates new car",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tariffs"
                ],
                "summary": "Creates a new car",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TariffCreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/TariffMessageResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tariff/{id}/detail/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve single tariff detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tariffs"
                ],
                "summary": "Retrieve single tariff",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tariff ID (int)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TariffResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tariff/{id}/update/": {
            "patch": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Updates an existing tariff",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tariffs"
                ],
                "summary": "Update a tariff",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tariff ID (int)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TariffUpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/TariffMessageResponse"
                        }
                    },
                    "400": {
                        "description": "detail: BadRequest - invalid request",
                        "schema": {
                            "$ref": "#/definitions/BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "404": {
                        "description": "detail: User not found",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-session/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a list of users with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Retrieves all users with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserSessionExtendedPaginatedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-session/{id}/detail/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve single user session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Retrieve single user session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User session ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserSessionExtendedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user-session/{id}/revoke/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a list of users with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Retrieves all user sessions with pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User session ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/MessagedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a list of users with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Retrieves all users with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "User activity",
                        "name": "is_active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserPaginatedResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/count/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieves a count of users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Count all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "User activity",
                        "name": "is_active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "count: 12345",
                        "schema": {
                            "$ref": "#/definitions/CountResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/create/": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Creates new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create and response new user",
                "parameters": [
                    {
                        "description": "User create Data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserCreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/UserMessageResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}/delete/": {
            "delete": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Deletes a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/UserMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}/detail/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve single user detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Retrieve single user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}/update/": {
            "patch": {
                "security": [
                    {
                        "OAuth2Password": [
                            ""
                        ]
                    }
                ],
                "description": "Updates user data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update Data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserUpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/UserMessageResponse"
                        }
                    },
                    "400": {
                        "description": "detail: BadRequest - invalid request",
                        "schema": {
                            "$ref": "#/definitions/BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "detail: Unauthorized - Invalid token",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedResponse"
                        }
                    },
                    "403": {
                        "description": "detail: Permission denied",
                        "schema": {
                            "$ref": "#/definitions/PermissionDeniedResponse"
                        }
                    },
                    "404": {
                        "description": "detail: User not found",
                        "schema": {
                            "$ref": "#/definitions/NotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "detail: Validation errors",
                        "schema": {
                            "$ref": "#/definitions/ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "detail: Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "BadRequestResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "BadRequest - invalid request"
                }
            }
        },
        "CameraCreateInput": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "channelName": {
                    "type": "string",
                    "maxLength": 255
                },
                "channelToken": {
                    "type": "string",
                    "maxLength": 255
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "type": {
                    "$ref": "#/definitions/CameraType"
                }
            }
        },
        "CameraMessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/CameraResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "CameraPaginatedResponse": {
            "type": "object",
            "required": [
                "limit",
                "page",
                "rows"
            ],
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CameraResponse"
                    }
                }
            }
        },
        "CameraResponse": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "name",
                "type"
            ],
            "properties": {
                "channelName;": {
                    "type": "string"
                },
                "channelToken;": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/ChoiceBase"
                },
                "updatedAt": {
                    "description": "optional",
                    "type": "string"
                }
            }
        },
        "CameraType": {
            "type": "string",
            "enum": [
                "inside",
                "outside"
            ],
            "x-enum-varnames": [
                "InsideCamera",
                "OutsideCamera"
            ]
        },
        "CameraUpdateInput": {
            "type": "object",
            "properties": {
                "channelName": {
                    "type": "string",
                    "maxLength": 255
                },
                "channelToken": {
                    "type": "string",
                    "maxLength": 255
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "type": {
                    "$ref": "#/definitions/CameraType"
                }
            }
        },
        "CarCreateInput": {
            "type": "object",
            "required": [
                "carNumber"
            ],
            "properties": {
                "carNumber": {
                    "type": "string",
                    "maxLength": 255
                },
                "isStaff": {
                    "type": "boolean"
                },
                "ownerName": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "CarMessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/CarResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "CarPaginatedResponse": {
            "type": "object",
            "required": [
                "limit",
                "page",
                "rows"
            ],
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CarResponse"
                    }
                }
            }
        },
        "CarParkType": {
            "type": "string",
            "enum": [
                "P1",
                "P2",
                "P3",
                "P4"
            ],
            "x-enum-varnames": [
                "Park1",
                "Park2",
                "Park3",
                "Park4"
            ]
        },
        "CarResponse": {
            "type": "object",
            "required": [
                "carNumber",
                "createdAt",
                "id",
                "isStaff"
            ],
            "properties": {
                "carNumber": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isStaff": {
                    "type": "boolean"
                },
                "ownerName": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "optional, can be nil",
                    "type": "string"
                }
            }
        },
        "CarSessionMessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/CarSessionResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "CarSessionPaginatedResponse": {
            "type": "object",
            "required": [
                "limit",
                "page",
                "rows"
            ],
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CarSessionResponse"
                    }
                }
            }
        },
        "CarSessionResponse": {
            "type": "object",
            "required": [
                "carId",
                "createdAt",
                "currency",
                "id",
                "isPaid",
                "status"
            ],
            "properties": {
                "cameraId": {
                    "type": "integer"
                },
                "cameraToken": {
                    "type": "string"
                },
                "car": {
                    "$ref": "#/definitions/CarResponse"
                },
                "carId": {
                    "type": "integer"
                },
                "carPark": {
                    "$ref": "#/definitions/ChoiceBase"
                },
                "createdAt": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageUrl": {
                    "type": "string"
                },
                "isPaid": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/ChoiceBase"
                },
                "totalAmount": {
                    "type": "number"
                },
                "updatedAt": {
                    "description": "optional, can be nil",
                    "type": "string"
                }
            }
        },
        "CarUpdateInput": {
            "type": "object",
            "properties": {
                "carNumber": {
                    "type": "string",
                    "maxLength": 255
                },
                "isStaff": {
                    "type": "boolean"
                },
                "ownerName": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "ChoiceBase": {
            "type": "object",
            "required": [
                "label",
                "value"
            ],
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "CountResponse": {
            "type": "object",
            "required": [
                "count"
            ],
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 12345
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Invalid request body"
                }
            }
        },
        "InternalServerErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Internal Server Error"
                }
            }
        },
        "LoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "carPark": {
                    "$ref": "#/definitions/CarParkType"
                },
                "password": {
                    "type": "string",
                    "maxLength": 150
                },
                "username": {
                    "type": "string",
                    "maxLength": 150
                }
            }
        },
        "LoginResponse": {
            "type": "object",
            "required": [
                "access_token",
                "role"
            ],
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/RoleType"
                        }
                    ],
                    "example": "operator"
                }
            }
        },
        "MessagedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "NotFoundResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Not found"
                }
            }
        },
        "PermissionDeniedResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Permission denied"
                }
            }
        },
        "RoleType": {
            "type": "string",
            "enum": [
                "admin",
                "operator",
                "accountant"
            ],
            "x-enum-varnames": [
                "AdminRole",
                "OperatorRole",
                "AccountantRole"
            ]
        },
        "TariffCreateInput": {
            "type": "object",
            "required": [
                "duration",
                "name",
                "price_amount"
            ],
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "price_amount": {
                    "type": "number"
                }
            }
        },
        "TariffMessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/TariffResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "TariffPaginatedResponse": {
            "type": "object",
            "required": [
                "limit",
                "page",
                "rows"
            ],
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TariffResponse"
                    }
                }
            }
        },
        "TariffResponse": {
            "type": "object",
            "required": [
                "PriceAmount",
                "createdAt",
                "currency",
                "duration",
                "id",
                "isActive",
                "name"
            ],
            "properties": {
                "PriceAmount": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "optional, can be nil",
                    "type": "string"
                }
            }
        },
        "TariffUpdateInput": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "price_amount": {
                    "type": "number"
                }
            }
        },
        "UnauthorizedResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Unauthorized - Invalid token"
                }
            }
        },
        "UserCreateInput": {
            "type": "object",
            "required": [
                "fullName",
                "password",
                "role",
                "username"
            ],
            "properties": {
                "carPark": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/CarParkType"
                        }
                    ]
                },
                "fullName": {
                    "type": "string",
                    "maxLength": 255
                },
                "isActive": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8,
                    "example": "secret-word"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/RoleType"
                        }
                    ],
                    "example": "operator"
                },
                "username": {
                    "type": "string",
                    "maxLength": 150
                }
            }
        },
        "UserMessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/UserResponse"
                        }
                    ],
                    "x-nullable": "true"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "UserPaginatedResponse": {
            "type": "object",
            "required": [
                "limit",
                "page",
                "rows"
            ],
            "properties": {
                "limit": {
                    "description": "items per page",
                    "type": "integer"
                },
                "page": {
                    "description": "current page",
                    "type": "integer"
                },
                "rows": {
                    "description": "generic slice of any type",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/UserResponse"
                    }
                }
            }
        },
        "UserResponse": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "isActive",
                "role",
                "username"
            ],
            "properties": {
                "carPark": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ChoiceBase"
                        }
                    ]
                },
                "createdAt": {
                    "type": "string"
                },
                "fullName": {
                    "description": "required in TS, can be empty",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "role": {
                    "$ref": "#/definitions/ChoiceBase"
                },
                "updatedAt": {
                    "description": "optional, can be nil",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "UserSessionExtendedPaginatedResponse": {
            "type": "object",
            "required": [
                "limit",
                "page",
                "rows"
            ],
            "properties": {
                "limit": {
                    "description": "items per page",
                    "type": "integer"
                },
                "page": {
                    "description": "current page",
                    "type": "integer"
                },
                "rows": {
                    "description": "generic slice of any type",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/UserSessionExtendedResponse"
                    }
                }
            }
        },
        "UserSessionExtendedResponse": {
            "type": "object",
            "required": [
                "createdAt",
                "expireAt",
                "id"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "expireAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "ipAddress": {
                    "type": "string",
                    "example": "192.168.1.1"
                },
                "macPassword": {
                    "type": "string",
                    "example": "mac-password"
                },
                "macUsername": {
                    "type": "string",
                    "example": "mac-username"
                },
                "revokedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/UserResponse"
                },
                "userAgent": {
                    "type": "string",
                    "example": "Mozilla/5.0"
                }
            }
        },
        "UserUpdateInput": {
            "type": "object",
            "properties": {
                "carPark": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/CarParkType"
                        }
                    ]
                },
                "fullName": {
                    "type": "string",
                    "maxLength": 255
                },
                "isActive": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8,
                    "example": "secret-word"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/RoleType"
                        }
                    ],
                    "example": "operator"
                },
                "username": {
                    "type": "string",
                    "maxLength": 150
                }
            }
        },
        "ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Validation error"
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "fieldName": "this field is required"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "/api/v1/auth/login",
            "scopes": {
                "read": "Grants read access",
                "write": "Grants write access"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Openapi spec",
	Description:      "This is a sample Fiber API with OAuth2 password flow",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
